[auth]
redirect_uri  = "http://localhost:8501/oauth2callback"
cookie_secret = "run: python -c 'import secrets; print(secrets.token_hex(32))'"
client_id     = "792327793652-o184mknk3mms8rqema13h1m2ddtps2pr.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"